package app.aaps.plugins.constraints.objectives.objectives

import app.aaps.plugins.constraints.R
import dagger.android.HasAndroidInjector

@Suppress("SpellCheckingInspection")
class Objective2(injector: HasAndroidInjector) : Objective(injector, "exam", R.string.objectives_exam_objective, R.string.objectives_exam_gate) {

    init {
        tasks.add(
            ExamTask(this, R.string.prerequisites_label, R.string.prerequisites_what, "prerequisites")
                .option(Option(R.string.prerequisites_nightscout, true))
                .option(Option(R.string.prerequisites_computer, true))
                .option(Option(R.string.prerequisites_pump, true))
                .option(Option(R.string.prerequisites_beanandroiddeveloper, true))
                .hint(Hint(R.string.prerequisites_hint1))
                .learned(Learned(R.string.objectives_exam_learned_prerequisites))
        )
        tasks.add(
            ExamTask(this, R.string.prerequisites2_label, R.string.prerequisites2_what, "prerequisites2")
                .option(Option(R.string.prerequisites2_profile, true))
                .option(Option(R.string.prerequisites2_device, true))
                .option(Option(R.string.prerequisites2_internet, true))
                .option(Option(R.string.prerequisites2_supportedcgm, true))
                .hint(Hint(R.string.prerequisites2_hint1))
                .learned(Learned(R.string.objectives_exam_learned_prerequisites2))
        )
        tasks.add(
            ExamTask(this, R.string.basaltest_label, R.string.basaltest_when, "basaltest")
                .option(Option(R.string.basaltest_fixed, true))
                .option(Option(R.string.basaltest_havingregularhighlow, true))
                .option(Option(R.string.basaltest_weekly, true))
                .option(Option(R.string.basaltest_beforeloop, true))
                .hint(Hint(R.string.basaltest_hint1))
                .learned(Learned(R.string.objectives_exam_learned_basaltest))
        )
        tasks.add(
            ExamTask(this, R.string.dia_label_exam, R.string.dia_whatmeansdia, "dia")
                .option(Option(R.string.dia_profile, true))
                .option(Option(R.string.dia_minimumis5h, true))
                .option(Option(R.string.dia_meaningisequaltodiapump, true))
                .option(Option(R.string.dia_valuemustbedetermined, true))
                .hint(Hint(R.string.dia_hint1))
                .learned(Learned(R.string.objectives_exam_learned_dia))
        )
        tasks.add(
            ExamTask(this, R.string.isf_label_exam, R.string.blank, "isf")
                .option(Option(R.string.isf_decreasingvalue, true))
                .option(Option(R.string.isf_preferences, true))
                .option(Option(R.string.isf_increasingvalue, true))
                .option(Option(R.string.isf_noeffect, true))
                .hint(Hint(R.string.isf_hint1))
                .hint(Hint(R.string.isf_hint2))
                .learned(Learned(R.string.objectives_exam_learned_isf))
        )
        tasks.add(
            ExamTask(this, R.string.ic_label_exam, R.string.blank, "ic")
                .option(Option(R.string.ic_increasingvalue, true))
                .option(Option(R.string.ic_decreasingvalue, true))
                .option(Option(R.string.ic_multiple, true))
                .option(Option(R.string.ic_isf, true))
                .hint(Hint(R.string.ic_hint1))
                .learned(Learned(R.string.objectives_exam_learned_ic))
        )
        tasks.add(
            ExamTask(this, R.string.hypott_label, R.string.hypott_whenhypott, "hypott")
                .option(Option(R.string.hypott_preventoversmb, true))
                .option(Option(R.string.hypott_exercise, true))
                .option(Option(R.string.hypott_wrongbasal, true))
                .option(Option(R.string.hypott_0basal, true))
                .hint(Hint(R.string.hypott_hint1))
                .learned(Learned(R.string.objectives_exam_learned_hypott))
        )
        tasks.add(
            ExamTask(this, R.string.profileswitch_label, R.string.profileswitch_pctwillchange, "profileswitch")
                .option(Option(R.string.profileswitch_basallower, true))
                .option(Option(R.string.profileswitch_isfhigher, true))
                .option(Option(R.string.profileswitch_iclower, true))
                .option(Option(R.string.profileswitch_unchanged, true))
                .hint(Hint(R.string.profileswitch_hint1))
                .learned(Learned(R.string.objectives_exam_learned_profileswitch))
        )
        tasks.add(
            ExamTask(this, R.string.profileswitch2_label, R.string.profileswitch2_pctwillchange, "profileswitch2")
                .option(Option(R.string.profileswitch2_bghigher, true))
                .option(Option(R.string.profileswitch2_basalhigher, true))
                .option(Option(R.string.profileswitch2_bgunchanged, true))
                .option(Option(R.string.profileswitch2_isfhigher, true))
                .hint(Hint(R.string.profileswitch_hint1))
        )
        tasks.add(
            ExamTask(this, R.string.profileswitchtime_label, R.string.profileswitchtime_iwant, "profileswitchtime")
                .option(Option(R.string.profileswitchtime_2, true))
                .option(Option(R.string.profileswitchtime__2, true))
                .option(Option(R.string.profileswitchtime_tt, true))
                .option(Option(R.string.profileswitchtime_100, true))
                .hint(Hint(R.string.profileswitchtime_hint1))
                .learned(Learned(R.string.objectives_exam_learned_profileswitchtime))
        )
        tasks.add(
            ExamTask(this, R.string.profileswitch4_label, R.string.blank, "profileswitch4")
                .option(Option(R.string.profileswitch4_rates, true))
                .option(Option(R.string.profileswitch4_internet, true))
                .option(Option(R.string.profileswitch4_sufficient, true))
                .option(Option(R.string.profileswitch4_multi, true))
                .hint(Hint(R.string.profileswitch_hint1))
                .learned(Learned(R.string.objectives_exam_learned_profileswitch4))
        )
        tasks.add(
            ExamTask(this, R.string.exerciseprofile_label, R.string.exerciseprofile_whattodo, "exercise")
                .option(Option(R.string.exerciseprofile_switchprofileabove100, true))
                .option(Option(R.string.exerciseprofile_switchprofilebelow100, true))
                .option(Option(R.string.exerciseprofile_suspendloop, true))
                .option(Option(R.string.exerciseprofile_leaveat100, true))
                .hint(Hint(R.string.exerciseprofile_hint1))
                .learned(Learned(R.string.objectives_exam_learned_exercise))
        )
        tasks.add(
            ExamTask(this, R.string.exercise_label, R.string.exercise_whattodo, "exercise2")
                .option(Option(R.string.exercise_settt, true))
                .option(Option(R.string.exercise_setfinished, true))
                .option(Option(R.string.exercise_setunchanged, true))
                .option(Option(R.string.exercise_15g, true))
                .hint(Hint(R.string.exercise_hint1))
                .learned(Learned(R.string.objectives_exam_learned_exercise2))
        )
        tasks.add(
            ExamTask(this, R.string.noisycgm_label, R.string.noisycgm_whattodo, "noisycgm")
                .option(Option(R.string.noisycgm_nothing, true))
                .option(Option(R.string.noisycgm_pause, true))
                .option(Option(R.string.noisycgm_replacesensor, true))
                .option(Option(R.string.noisycgm_checksmoothing, true))
                .hint(Hint(R.string.noisycgm_hint1))
                .learned(Learned(R.string.objectives_exam_learned_noisycgm))
        )
        tasks.add(
            ExamTask(this, R.string.pumpdisconnect_label, R.string.blank, "pumpdisconnect")
                .option(Option(R.string.pumpdisconnect_unnecessary, true))
                .option(Option(R.string.pumpdisconnect_missinginsulin, true))
                .option(Option(R.string.pumpdisconnect_notstop, true))
                .option(Option(R.string.pumpdisconnect_openloop, true))
                .hint(Hint(R.string.pumpdisconnect_hint1))
                .learned(Learned(R.string.objectives_exam_learned_pumpdisconnect))
        )
        tasks.add(
            ExamTask(this, R.string.insulin_plugins, R.string.insulin_ultrarapid, "insulin")
                .option(Option(R.string.insulin_novorapid, true))
                .option(Option(R.string.insulin_humalog, true))
                .option(Option(R.string.insulin_actrapid, true))
                .option(Option(R.string.insulin_fiasp, true))
                .hint(Hint(R.string.insulin_hint1))
                .learned(Learned(R.string.objectives_exam_learned_insulin))
        )
        tasks.add(
            ExamTask(this, R.string.sensitivity_label, R.string.blank, "sensitivity")
                .option(Option(R.string.sensitivity_adjust, true))
                .option(Option(R.string.sensitivity_edit, true))
                .option(Option(R.string.sensitivity_cannula, true))
                .option(Option(R.string.sensitivity_time, true))
                .hint(Hint(R.string.sensitivity_hint1))
                .hint(Hint(R.string.sensitivity_hint2))
                .learned(Learned(R.string.objectives_exam_learned_sensitivity))
        )
        tasks.add(
            ExamTask(this, R.string.objectives_label, R.string.objectives_howtosave, "objectives")
                .option(Option(R.string.objectives_notesettings, true))
                .option(Option(R.string.objectives_afterobjective, true))
                .option(Option(R.string.objectives_afterchange, true))
                .option(Option(R.string.objectives_afterinitialsetup, true))
                .hint(Hint(R.string.objectives_hint1))
                .hint(Hint(R.string.objectives_hint2))
                .learned(Learned(R.string.objectives_exam_learned_objectives))
        )
        tasks.add(
            ExamTask(this, R.string.objectives2_label, R.string.objectives_howtosave, "objectives2")
                .option(Option(R.string.objectives2_maintenance, true))
                .option(Option(R.string.objectives2_internalstorage, true))
                .option(Option(R.string.objectives2_cloud, true))
                .option(Option(R.string.objectives2_easyrestore, true))
                .hint(Hint(R.string.objectives_hint1))
                .hint(Hint(R.string.objectives_hint2))
                .learned(Learned(R.string.objectives_exam_learned_objectives2))
        )
        tasks.add(
            ExamTask(this, R.string.update_label, R.string.blank, "update")
                .option(Option(R.string.update_git, true))
                .option(Option(R.string.update_askfriend, true))
                .option(Option(R.string.update_keys, true))
                .option(Option(R.string.update_asap, true))
                .hint(Hint(R.string.update_hint1))
        )
        tasks.add(
            ExamTask(this, R.string.troubleshooting_label, R.string.troubleshooting_wheretoask, "troubleshooting")
                .option(Option(R.string.troubleshooting_fb, true))
                .option(Option(R.string.troubleshooting_wiki, true))
                .option(Option(R.string.troubleshooting_gitter, true))
                .option(Option(R.string.troubleshooting_yourendo, true))
                .hint(Hint(R.string.troubleshooting_hint1))
                .hint(Hint(R.string.troubleshooting_hint2))
                .hint(Hint(R.string.troubleshooting_hint3))
        )
        tasks.add(
            ExamTask(this, R.string.wrongcarbs_label, R.string.wrongcarbs_whattodo, "wrongcarbs")
                .option(Option(R.string.wrongcarbs_addinsulin, true))
                .option(Option(R.string.wrongcarbs_treatmentstab, true))
                .option(Option(R.string.wrongcarbs_donothing, true))
                .option(Option(R.string.wrongcarbs_bolus, true))
                .learned(Learned(R.string.objectives_exam_learned_wrongcarbs))
        )
        tasks.add(
            ExamTask(this, R.string.wronginsulin_label, R.string.wronginsulin_whattodo, "wronginsulin")
                .option(Option(R.string.wronginsulin_careportal, true))
                .option(Option(R.string.wronginsulin_compare, true))
                .option(Option(R.string.wronginsulin_prime, true))
                .option(Option(R.string.wrongcarbs_donothing, true))
        )
        tasks.add(
            ExamTask(this, app.aaps.core.ui.R.string.iob_label, R.string.blank, "iob")
                .option(Option(R.string.iob_value, true))
                .option(Option(R.string.iob_hightemp, true))
                .option(Option(R.string.iob_negiob, true))
                .option(Option(R.string.iob_posiob, true))
                .learned(Learned(R.string.objectives_exam_learned_iob))
        )
        tasks.add(
            ExamTask(this, R.string.cob_label, R.string.cob_question, "cob1")
                .option(Option(R.string.cob_longer, true))
                .option(Option(R.string.cob_shorter, true))
                .option(Option(R.string.cob_no_effect, true))
                .hint(Hint(R.string.cob_hint1))
        )
        tasks.add(
            ExamTask(this, R.string.cob_label, R.string.cob2_question, "cob2")
                .option(Option(R.string.cob2_longer, true))
                .option(Option(R.string.cob2_shorter, true))
                .option(Option(R.string.cob2_no_effect, true))
                .hint(Hint(R.string.cob_hint1))
        )
        tasks.add(
            ExamTask(this, R.string.cob_label, R.string.cob3_question, "cob3")
                .option(Option(R.string.cob3_longer, true))
                .option(Option(R.string.cob3_shorter, true))
                .option(Option(R.string.cob3_no_effect, true))
                .hint(Hint(R.string.cob_hint1))
                .learned(Learned(R.string.objectives_exam_learned_cob))
        )
        tasks.add(
            ExamTask(this, R.string.breadgrams_label, R.string.blank, "breadgrams")
                .option(Option(R.string.breadgrams_grams, true))
                .option(Option(R.string.breadgrams_exchange, true))
                .option(Option(R.string.breadgrams_decay, true))
                .option(Option(R.string.breadgrams_calc, true))
                .hint(Hint(R.string.breadgrams_hint1))
                .learned(Learned(R.string.objectives_exam_learned_breadgrams))
        )
        tasks.add(
            ExamTask(this, R.string.extendedcarbs_label, R.string.extendedcarbs_handling, "extendedcarbs")
                .option(Option(R.string.extendedcarbs_future, true))
                .option(Option(R.string.extendedcarbs_free, true))
                .option(Option(R.string.extendedcarbs_fat, true))
                .option(Option(R.string.extendedcarbs_rescue, true))
                .hint(Hint(R.string.extendedcarbs_hint1))
                .learned(Learned(R.string.objectives_exam_learned_ecarbs))
        )
        tasks.add(
            ExamTask(this, R.string.nsclient_label, R.string.nsclient_howcanyou, "nsclient")
                .option(Option(R.string.nsclient_nightscout, true))
                .option(Option(R.string.nsclient_dexcomfollow, true))
                .option(Option(R.string.nsclient_data, true))
                .option(Option(R.string.nsclient_fullcontrol, true))
                .hint(Hint(R.string.nsclient_hint1))
                .learned(Learned(R.string.objectives_exam_learned_nsclient))
        )
        tasks.add(
            ExamTask(this, R.string.other_medication_label, R.string.other_medication_text, "otherMedicationWarning")
                .option(Option(app.aaps.core.ui.R.string.yes, true))
                .option(Option(app.aaps.core.ui.R.string.no, true))
        )
        for (task in tasks) (task as ExamTask).options.shuffle()

        for (task in tasks) {
            if (!task.isCompleted()) accomplishedOn = 0
        }
    }
}